monsieurbiz_sylius_search_search:
    path: /search/{query}
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController::searchAction
    requirements:
        query: .+

monsieurbiz_sylius_search_post:
    path: /search
    methods: [POST]
    defaults:
        _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController::postAction

monsieurbiz_sylius_search_instant:
    path: /instant
    methods: [POST]
    defaults:
        _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController::instantAction

monsieurbiz_sylius_search_taxon:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController::taxonAction
    requirements:
        slug: .+
