version: "3.4"

services:
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=sylius_search_plugin_test
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=sylius
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql:rw
    
    elasticsearch:
        build:
            context: ./.docker/elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data:rw
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"

volumes:
    mysql_data:
    elasticsearch-data:
