version: "3.4"

services:
    app:
        image: sylius/standard:1.11-traditional-alpine
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Rome"
            MONSIEURBIZ_SEARCHPLUGIN_ES_HOST: "elasticsearch"
            MONSIEURBIZ_SEARCHPLUGIN_ES_PORT: "9200"
        volumes:
            - ./:/app:delegated
            - ./.docker/php/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=sylius_search_plugin_test
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=sylius
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql:rw
    
    elasticsearch:
        build:
            context: ./.docker/elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data:rw
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - sylius

    elastichq:
        image: elastichq/elasticsearch-hq
        environment:
            - HQ_DEFAULT_URL=http://elasticsearch:9200
        ports:
            - "5000:5000"
        networks:
            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    mysql_data:
    elasticsearch-data:
