filter:
  search_autocomplete_filter:
    type:     'edge_ngram'
    min_gram: 1
    max_gram: 20
analyzer:
  search_autocomplete:
    type:      'custom'
    tokenizer: 'icu_tokenizer'
    filter:    [ 'lowercase', 'icu_folding', 'elision', 'search_autocomplete_filter' ]
  search_standard:
    type:      'custom'
    tokenizer: 'icu_tokenizer'
    filter:    [ 'lowercase', 'icu_folding', 'elision' ]
