---
# Search query, sorts and filters are managed dynamically
query:
  bool:
    filter:
      - term:
          enabled: true
      - term:
          inStock: true
      - term:
          channel: "{{CHANNEL}}"
    must:
      - bool:
          should:
            - term:
                code: "{{QUERY}}"
            - nested:
                path: attributes
                query:
                  - bool:
                      filter:
                        - multi_match:
                            query: "{{QUERY}}"
                            fields:
                              - attributes.value
                            fuzziness: 1
                      should:
                        - rank_feature:
                            field: attributes.score
                        - multi_match:
                            query: "{{QUERY}}"
                            fields:
                              - attributes.value^2
    should:
      - nested:
          path: attributes
          query:
            - bool:
                must:
                  - multi_match:
                      query: "{{QUERY}}"
                      fields:
                        - attributes.value^6
                  - multi_match:
                      query: "name"
                      fields:
                        - attributes.code
            - bool:
                must:
                  - multi_match:
                      query: "{{QUERY}}"
                      fields:
                        - attributes.value^4
                      fuzziness: 1
                  - multi_match:
                      query: "name"
                      fields:
                        - attributes.code
