---
# Taxon query, sorts and filters are managed dynamically
query:
  bool:
    filter:
      - term:
          enabled: true
      - term:
          inStock: true
      - term:
          channel: "{{CHANNEL}}"
    must:
      nested:
        path: taxon
        query:
          bool:
            must:
              term:
                taxon.code:
                  value: "{{TAXON}}"
