# Add JS for plugin for Sylius 2.0
#sylius_ui:
#    events:
#        sylius.shop.layout.javascripts:
#            blocks:
#                monsieur_biz_sylius_search_js:
#                    template: "@MonsieurBizSyliusSearchPlugin/js.html.twig"
#                    priority: 0
